### ISSUE TITLE
Bug with vertical orientation + text color

### ISSUE THREAD

**Issue by lowercase00** [greghub/vue-funnel-graph-js#2]
Thanks for the component, amazing library indeed.

While trying to use it, I have found two problems. When making my code default to `vertical` direction the text overwrites the chart (as the picture below). The same happend when using the `Toggle Direction` button.

Also, I couldn't find information on how to change text colors - when using light backgrounds I lose both the legend and the numbers info.

Any ideas?
Thanks
![Screen Shot 2019-06-07 at 04 12 14](https://user-images.githubusercontent.com/21188280/59087243-7c3aff00-88da-11e9-9ed7-0b924cb2fc8b.png)

**Comment by greghub** [comment]
Hi @lowercase00 , thanks a lot. I did not create library options to change colors on purpose, because everything can be changed with CSS. I've set class names to all the elements, such as "svg-funnel-js__label", "label__value", "label__title". In your CSS you can set the label colors to a dark one, as well as position them. 
Please try editing it with your CSS
